creative_page/urls.py
# -*- coding: utf-8 -*-
# All Rights Reserved 
# @Time    : 2022/12/1023:01
# @Author  : Small Fu
# @Email   : 2737454073@qq.com
# @File    : urls.py
__author__ = 'Small Fu'

from django.urls import path
from creative_page import views

urlpatterns = [
    path("jtcsy", views.jtcsy, name="jtcsy"),
]

notebooks/urls.py
from django.urls import path
from notebooks.views import authentication
from notebooks.views import home

urlpatterns = [
    # path("", views.index, name="notebook_index"),
    path("login/", authentication.Login.as_view(), name="login"),
    path("register/", authentication.Register.as_view(), name="register"),
]

websiteBook/urls.py
from websiteBook import settings
from notebooks.views import home
from creative_page import views
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf.urls.static import static
from django.urls import re_path  # 因为需要用到正则匹配所以导入它

urlpatterns = [
                  # 后台管理
                  path('admin/', admin.site.urls),

                  # 首页
                  path("", home.Home.as_view(), name="home"),
                  # 表白
                  path("xiaofu_xiaochen", views.xiaofu_xiaochen, name="xiaofu_xiaochen"),

                  # 笔记页
                  path('notebooks/', include(("notebooks.urls", "notebooks"), namespace="notebook")),
                  # 创意页面
                  path('creative_page/', include(("creative_page.urls", "creative_page"), namespace="creative_pages")),
                  # 静态文件加载问题
                  re_path('^static/(?P<path>.*)', serve, {'document_root': settings.STATIC_ROOT}),  # 用于处理static里的文件

                  re_path('^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),  # 用于处理上传的文件
              ]

"""
                              _ooOoo_
                             o8888888o
                             88" . "88
                             (| -_- |)
                             O\  =  /O
                          ____/`---'\____
                        .'  \\|     |//  `.
                       /  \\|||  :  |||//  \
                      /  _||||| -:- |||||-  \
                      |   | \\\  -  /// |   |
                      | \_|  ''\---/''  |   |
                      \  .-\__  `-`  ___/-. /
                    ___`. .'  /--.--\  `. . __
                 ."" '<  `.___\_<|>_/___.'  >'"".
                | | :  `- \`.;`\ _ /`;.`/ - ` : | |
                \  \ `-.   \_ __\ /__ _/   .-` /  /
           ======`-.____`-.___\_____/___.-`____.-'======
                              `=---='
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      佛祖保佑        永无BUG
             佛曰:
                    写字楼里写字间，写字间里程序员；
                    程序人员写程序，又拿程序换酒钱。
                    酒醒只在网上坐，酒醉还来网下眠；
                    酒醉酒醒日复日，网上网下年复年。
                    但愿老死电脑间，不愿鞠躬老板前；
                    奔驰宝马贵者趣，公交自行程序员。
                    别人笑我忒疯癫，我笑自己命太贱；
                    不见满街漂亮妹，哪个归得程序员？
"""

creative_page/models.py
from django.db import models

# Create your models here.

notebooks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
# class UserInfo(AbstractUser):
#     phone = models.CharField(max_length=32, verbose_name="手机号", null=True, blank=True)
#     """
#     null=True 数据库可以为空
#     blank=True 后台管理可以为空
#     """
#
#     create_time = models.DateField(auto_now_add=True, verbose_name="创建时间")
#
#     def __str__(self):
#         return self.username
#
#     class Meta:
#         verbose_name_plural = "用户表"


# class Article(models.Model):
#     title = models.CharField(verbose_name="文章标题", max_length=64)
#     desc = models.CharField(verbose_name="文章简介", max_length=255)
#     # 文章内容有很多，一般情况下都是使用TextFiled()
#     content = models.TextField(verbose_name="文章内容")
#
#     create_time = models.DateField(auto_now_add=True, verbose_name="创建时间")

creative_page/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_page


# Create your views here.
@cache_page(60 * 60)
def jtcsy(requests):
    return render(requests, "creative_page/今天吃啥呀？.html")


@cache_page(60 * 60)
def xiaofu_xiaochen(requests):
    return render(requests, "creative_page/表白.html")

notebooks/views/authentication.py
# -*- coding: utf-8 -*-
# All Rights Reserved 
# @Time    : 2022/11/1419:55
# @Author  : Small Fu
# @Email   : 2737454073@qq.com
# @File    : authentication.py
__author__ = 'Small Fu'

from django.views import View
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, reverse


class Login(View):
    def get(self, requests):
        return render(requests, "notebooks/authentication/login.html", locals())

    def post(self, requests):
        print(requests)
        back_dict = {"code":200}
        back_dict["code"] = 2001
        back_dict["msg"] = "失败"
        return JsonResponse(back_dict)


class Register(View):
    def get(self, requests):
        return HttpResponse("Register get")

    def post(self, requests):
        return HttpResponse("Register post")

notebooks/views/home.py
from django.shortcuts import render
from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page


# Create your views here.
class Home(View):

    @method_decorator(cache_page(24 * 60 * 60))
    def get(self, requests):
        return render(requests, "home.html", locals())

    def post(self, requests):
        pass

templates/creative_page/今天吃啥呀？.html
{% load static %}
<!DOCTYPE html>

<!-- saved from url=(0025)http://guozhivip.com/eat/ -->
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>今天吃啥呀？</title>
    <meta name="keywords" content="今天吃啥呀-小符为您服务">
    <meta name="description" content="随机推荐食品，再也不用为今天吃什么发愁了。">
    <link rel="stylesheet" type="text/css" href="{% static 'creative_page/jtcsy/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'creative_page/jtcsy/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'creative_page/jtcsy/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'creative_page/jtcsy/eat-min.css' %}">

</head>

<body style="display: block;" class="col-xs-12 col-md-12 col-sm-12">
<div class="logo"><img src="{% static 'creative_page/jtcsy/logo.png' %}"></div>
<div id="wrapper">
    <h1 style="color:#FF9733" id="what"></h1>
    <input type="button" value="开始" id="start">
    <p><span id="cfg" title="编辑候选菜单"><i class="fa fa-pencil"></i>&nbsp;自定义</span><a
            href="javascript:location.reload();" id="cx" style="display: none">
        <i class="fa fa-undo"></i>&nbsp;重选</a></p>
</div>

<div id="popbox-wrapper" style="display: none;">
    <div id="popbox">
        <h3>自定义临时菜单<br><small
                style="display:block;color: #666; font-size: 12px; font-weight: 100;margin-top: 3px;">- 菜名间要以空格区分
            -</small></h3>
        <textarea type="hidden" id="list" name="list"
                  placeholder="在此输入菜单，各菜名间以空格分隔...">馄饨 烩面 热干面 刀削面 油泼面 炸酱面 炒面 重庆小面 米线 酸辣粉 土豆粉 螺狮粉 凉皮儿 麻辣烫 肉夹馍 羊肉泡馍 炒饭 盖浇饭 烤肉饭 黄焖鸡米饭 麻辣香锅 火锅 酸菜鱼 烤串 披萨 烤鸭 汉堡 炸鸡 寿司 煎饼果子 南瓜粥 小龙虾 牛排 砂锅 大排档 馒头 西餐 自助餐 小笼包 水果 西北风 烧烤 泡面 水饺 日本料理 涮羊肉 兰州拉面 肯德基 面包 臊子面 小笼包 麦当劳 沙县小吃 烤鱼 海鲜 铁板烧 韩国料理 甜点 鸭血粉丝汤 </textarea>
        <input type="button" value="确定" id="ok">
    </div>
</div>

<footer>

</footer>

<script src="{% static 'creative_page/jtcsy/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'creative_page/jtcsy/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'creative_page/jtcsy/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'creative_page/jtcsy/hm.js' %}"></script>

<script>
    $(function () {
        var run = 0,
            btn = $("#start"),
            popup = $("#popbox-wrapper"),
            li = $("#list"),
            times = 0,
            timer;

        $("#start").click(function () {
            var list = $("#list").val().replace(/ +/g, " ").replace(/^ | $/g, "").split(" ");
            if (list.length == 1 && list[0] != "") return alert("耍我是吧，一个有什么好选的！");
            if (list.length == 1) return alert("菜单中啥也没有，吃西北风去啊？");
            if (!run) {
                $("#cfg").add(btn).one("click", function () {
                    $(".tip").animate({
                        left: "+=10px",
                        opacity: 0
                    }, function () {
                        $(this).remove();
                    });
                });
                $(this).val("停止");
                timer = setInterval(function () {
                    var r = Math.ceil(Math.random() * list.length),
                        food = list[r - 1];
                    $("#what").html(food);
                    var rTop = Math.ceil(Math.random() * $(document).height()),
                        rLeft = Math.ceil(Math.random() * ($(document).width() - 50)),
                        rSize = Math.ceil(Math.random() * (37 - 14) + 14);
                    $("<span class='temp'></span>").html(food).hide().css({
                        "top": rTop,
                        "left": rLeft,
                        "color": "rgba(0,0,0,." + Math.random() + ")",
                        "fontSize": rSize + "px"
                    }).appendTo("body").fadeIn("slow", function () {
                        $(this).fadeOut("slow", function () {
                            $(this).remove();
                        });
                    });
                }, 50);
                run = 1;
            } else {
                $(this).val("不行，换一个");
                clearInterval(timer);
                run = 0;
            }
            ;
        });
        $("#cfg").click(function () {
            run ? alert("还在选呢！") : popup.fadeIn(function () {
                var t = li.val();
                li.focus().val("").val(t)
            });
        });

        $("#ok").click(function () {
            popup.fadeOut();
        });
    });

    $i = 0;
    $('#start').click(function () {
        $i++;
        if ($i >= 12) {
            $('#start').hide();
            $('#what').html('这么挑？饿着吧！');
            $('#cfg').hide();
            $('#cx').show();
        }
        ;
    })


</script>
<!--tm-->
<script type="text/javascript">
    window.onload = function () {
        showTime();
    }

    function showTime() {
        var now = new Date();
        var year = now.getFullYear();
        document.getElementById("show").innerHTML = "" + year;
        t = setTimeout('showTime()', 1000)
    }
</script>

<script type="text/javascript">
    var h = $(window).height();
    $(window).resize(function () {
        if ($(window).height() < h) {
            $('.copyright').css("display", "none");
        } else {
            $('.copyright').css("display", "block");
        }
    });
</script>
<!--pb-->
<script>
    document.oncontextmenu = function (event) {
        if (window.event) {
            event = window.event;
        }
        try {
            var the = event.srcElement;
            if (!((the.tagName == "INPUT" && the.type.toLowerCase() == "text") || the.tagName == "TEXTAREA")) {
                return false;
            }
            return true;
        } catch (e) {
            return false;
        }
    }
</script>
{#<script>#}
{#    document.onkeydown = function () {#}
{##}
{#        if (window.event && window.event.keyCode == 123) {#}
{#            alert("Hi,欢迎来到果汁！");#}
{#            event.keyCode = 0;#}
{#            event.returnValue = false;#}
{#        }#}
{#        if (window.event && window.event.keyCode == 13) {#}
{#            window.event.keyCode = 505;#}
{#        }#}
{#        if (window.event && window.event.keyCode == 8) {#}
{#            alert(str + "\n请使用Del键进行字符的删除操作！");#}
{#            window.event.returnValue = false;#}
{#        }#}
{#    }#}
{#</script>#}

<script type="text/javascript">
    if (self == top) {
        var theBody = document.getElementsByTagName('body')[0];
        theBody.style.display = "block";
    } else {
        top.location = self.location;
    }
</script>
<!--tj-->
{#<script>#}
{#    var _hmt = _hmt || [];#}
{#    (function () {#}
{#        var hm = document.createElement("script");#}
{#        hm.src = "https://hm.baidu.com/hm.js?7c242ad25d63427a681f4ae84d4ffe19";#}
{#        var s = document.getElementsByTagName("script")[0];#}
{#        s.parentNode.insertBefore(hm, s);#}
{#    })();#}
{#</script>#}


</body>

</html>

templates/creative_page/表白.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>小符喜欢小陈</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        body, html {
            height: 100%;
            width: 100%;
            margin: 0 0 0 0;
            overflow: hidden hidden;
            background-color: #1E1E1E;

        }

    </style>
</head>
<body>

<canvas id="drawHeart" width="100%"></canvas>

<script>
    var hearts = [];
    var canvas = document.getElementById('drawHeart');
    var wW = window.innerWidth;
    var wH = window.innerHeight;
    // 创建画布
    var ctx = canvas.getContext('2d');
    // 创建图片对象
    var heartImage = new Image();
    heartImage.src = "../../static/img/creative_page/heart.svg";
    var num = 100;

    init();

    window.addEventListener('resize', function () {
        wW = window.innerWidth;
        wH = window.innerHeight;
    });

    // 初始化画布大小
    function init() {
        canvas.width = wW;
        canvas.height = wH;
        for (var i = 0; i < num; i++) {
            hearts.push(new Heart(i % 5));
        }
        requestAnimationFrame(render);
    }

    function getColor() {
        var val = Math.random() * 10;
        if (val > 0 && val <= 1) {
            return '#00f';
        } else if (val > 1 && val <= 2) {
            return '#f00';
        } else if (val > 2 && val <= 3) {
            return '#0f0';
        } else if (val > 3 && val <= 4) {
            return '#368';
        } else if (val > 4 && val <= 5) {
            return '#666';
        } else if (val > 5 && val <= 6) {
            return '#333';
        } else if (val > 6 && val <= 7) {
            return '#f50';
        } else if (val > 7 && val <= 8) {
            return '#e96d5b';
        } else if (val > 8 && val <= 9) {
            return '#5be9e9';
        } else {
            return '#d41d50';
        }
    }

    function getText() {
        /*
        var val = Math.random() * 10;

        if (val > 1 && val <= 3) {
            return '爱你一辈子';
        } else if (val > 3 && val <= 5) {
            return '喜欢小陈';
        } else if (val > 5 && val <= 8) {
            return '爱你呦';
        } else {
            return 'I Love You';
        }
         */
        var items = [
            '爱你一辈子',
            '喜欢小陈',
            '想和小陈睡觉觉',
            '小陈在干啥呀',
            '小陈你想我了吗！',
            '爱你小陈',
        ];

        return items[Math.floor(Math.random() * items.length)];
    }

    function Heart(type) {
        this.type = type;
        // 初始化生成范围
        this.x = Math.random() * wW;
        this.y = Math.random() * wH;

        this.opacity = Math.random() * .5 + .5;

        // 偏移量
        this.vel = {
            x: (Math.random() - .5) * 5,
            y: (Math.random() - .5) * 5
        }

        this.initialW = wW * .5;
        this.initialH = wH * .5;
        // 缩放比例
        this.targetScale = Math.random() * .15 + .02; // 最小0.02
        this.scale = Math.random() * this.targetScale;

        // 文字位置
        this.fx = Math.random() * wW;
        this.fy = Math.random() * wH;
        this.fs = Math.random() * 10;
        this.text = getText();

        this.fvel = {
            x: (Math.random() - .5) * 5,
            y: (Math.random() - .5) * 5,
            f: (Math.random() - .5) * 2
        }
    }

    Heart.prototype.draw = function () {
        ctx.save();
        ctx.globalAlpha = this.opacity;
        ctx.drawImage(heartImage, this.x, this.y, this.width, this.height);
        ctx.scale(this.scale + 1, this.scale + 1);
        if (!this.type) {
            // 设置文字属性
            ctx.fillStyle = getColor();
            ctx.font = 'italic ' + this.fs + 'px sans-serif';
            // 填充字符串
            ctx.fillText(this.text, this.fx, this.fy);
        }
        ctx.restore();
    }
    Heart.prototype.update = function () {
        this.x += this.vel.x;
        this.y += this.vel.y;

        if (this.x - this.width > wW || this.x + this.width < 0) {
            // 重新初始化位置
            this.scale = 0;
            this.x = Math.random() * wW;
            this.y = Math.random() * wH;
        }
        if (this.y - this.height > wH || this.y + this.height < 0) {
            // 重新初始化位置
            this.scale = 0;
            this.x = Math.random() * wW;
            this.y = Math.random() * wH;
        }

        // 放大
        this.scale += (this.targetScale - this.scale) * .1;
        this.height = this.scale * this.initialH;
        this.width = this.height * 1.4;

        // -----文字-----
        this.fx += this.fvel.x;
        this.fy += this.fvel.y;
        this.fs += this.fvel.f;

        if (this.fs > 50) {
            this.fs = 2;
        }

        if (this.fx - this.fs > wW || this.fx + this.fs < 0) {
            // 重新初始化位置
            this.fx = Math.random() * wW;
            this.fy = Math.random() * wH;
        }
        if (this.fy - this.fs > wH || this.fy + this.fs < 0) {
            // 重新初始化位置
            this.fx = Math.random() * wW;
            this.fy = Math.random() * wH;
        }
    }

    function render() {
        ctx.clearRect(0, 0, wW, wH);
        for (var i = 0; i < hearts.length; i++) {
            hearts[i].draw();
            hearts[i].update();
        }
        requestAnimationFrame(render);
    }
</script>
</body>
</html>

templates/home.html
{% extends 'home_base.html' %}
{% load static %}

{% block css %}
    <style>
        .col-md-4 {
            padding-left: 5px;
            padding-right: 5px;
        }

        .img-size-50 {
            width: 50px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-lg-4">
                <div class="panel panel-danger" onclick=GoToPath("{% url 'creative_pages:jtcsy' %}")>
                    <div class="panel-heading ">
                        <img src="{% static 'img/home/今天吃啥子.gif' %}" alt="今天吃啥子" class="img-rounded img-size-50 ">
                        <span class="text-center">今天吃啥子</span>
                    </div>
                    <div class="panel-body">
                        可以随机抽取今天吃什么，还支持自定义
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-lg-4">
                <div class="panel panel-danger">
                    <div class="panel-heading">Panel heading without title</div>
                    <div class="panel-body">
                        Panel content
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-lg-4">
                <div class="panel panel-danger">
                    <div class="panel-heading">Panel heading without title</div>
                    <div class="panel-body">
                        Panel content
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        const GoToPath = function (UrlPath) {
            console.log(UrlPath)
            let ConF = window.confirm("是否要跳转");
            if (ConF) {
                window.location.href = UrlPath
            }
        };
    </script>
{% endblock %}

templates/home_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style>
        /*********LoadingPage*************/

        #loading {
            position: absolute;
            background-color: #FFF;: top: 0 px;
            left: 0px;
            width: 100%;
            height: 100%;
            z-index: 9999;
        }

        #loading_bg {
            background-color: rgba(0, 0, 0, 0.7);
        }

        body {
            background: #eaecfa;

        }

        .loader {
            width: 250px;
            height: 50px;
            line-height: 50px;
            text-align: center;
            position: absolute;
            top: 50%;
            left: 50%;

            -webkit-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            font-family: helvetica, arial, sans-serif;
            text-transform: uppercase;
            font-weight: 900;
            color: #ce4233;
            letter-spacing: 0.2em;
        }

        .loader::before, .loader::after {
            content: "";
            display: block;
            width: 15px;
            height: 15px;
            background: #ce4233;
            position: absolute;
            -webkit-animation: load .7s infinite alternate ease-in-out;
            animation: load .7s infinite alternate ease-in-out;
        }

        .loader::before {
            top: 0;
        }

        .loader::after {
            bottom: 0;
        }

        @-webkit-keyframes load {
            0% {
                left: 0;
                height: 30px;
                width: 15px;
            }
            50% {
                height: 8px;
                width: 40px;
            }
            100% {
                left: 235px;
                height: 30px;
                width: 15px;
            }
        }

        @keyframes load {
            0% {
                left: 0;
                height: 30px;
                width: 15px;
            }
            50% {
                height: 8px;
                width: 40px;
            }
            100% {
                left: 235px;
                height: 30px;
                width: 15px;
            }
        }

        /********************************/

    </style>

    {% block css %}

    {% endblock %}
</head>
<body>
<div id="loading">
    <div id="loading_bg">
        <div class="loader">Loading...</div>
    </div>
</div>

<nav class="navbar container navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home' %}">HOME</a>
        </div>
        <p class="navbar-text">小符的网站</p>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">
                {% if requests.user.is_authenticated %}
                    <li><a href="#">{{ requests.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true"
                           aria-expanded="false">更多操作<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">修改密码</a></li>
                            <li><a href="#">后台管理</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">退出登录</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'notebook:register' %}">注册</a></li>
                    <li><a href="{% url 'notebook:login' %}">登录</a></li>
                {% endif %}

            </ul>
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <input type="text" class="form-control" id="search_content" placeholder="文章">
                </div>
                <button type="submit" class="btn btn-default" id="search">搜索</button>
            </form>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div id="id_div_container">
    {% block content %}

    {% endblock %}
</div>

<nav class="navbar container navbar-fixed-bottom">
    {% block bottom-content %}

    {% endblock %}
</nav>

<script>
    //Loading页面
    document.onreadystatechange = function () {
        if (document.readyState == "complete") {
            loadingFade();
        }
    }

    function loadingFade() {
        var opacity = 1;
        //var loadingPage=document.getElementById('loading');
        var loadingBackground = document.getElementById('loading_bg');
        var time = setInterval(function () {
            if (opacity <= 0) {
                clearInterval(time);
                //loadingPage.remove();
                $('#loading').remove();
            }

            loadingBackground.style.opacity = opacity;
            opacity -= 0.4;
        }, 100);
    }

    $("#search").click(function () {
        var TextInput = $("#search_content").val()
        if (TextInput.length > 0) {
            $.ajax({
                url: "{% url 'home' %}",
                type: "post",
                dataType: "json",
                data: {
                    "content": TextInput,
                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                },
                success: function (args) {

                }
            })
        } else {
            alert("要有搜索值才可以搜!!!")
        }

    })

</script>

{% block js %}

{% endblock %}
</body>
</html>

templates/notebooks/authentication/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block css %}

    {% endblock %}
</head>
<body>
{% block content %}

{% endblock %}

</body>
{% block js %}

{% endblock %}

</html>

templates/notebooks/authentication/login.html
{% extends 'notebooks/authentication/base.html' %}
{% block css %}
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        html {
            height: 100%;
        }

        body {
            height: 100%;
        }

        .div_container {
            height: 100%;
            background-image: linear-gradient(to right, #fbc2eb, #a6c1ee);
        }

        .login-wrapper {
            background-color: #fff;
            width: 388px;
            height: 588px;
            border-radius: 15px;
            padding: 0 50px;
            position: relative;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }

        .header {
            font-size: 38px;
            font-weight: bold;
            text-align: center;
            line-height: 200px;
        }

        .input-item {
            display: block;
            width: 100%;
            margin-bottom: 20px;
            border: 0;
            padding: 10px;
            border-bottom: 1px solid rgb(128, 125, 125);
            font-size: 15px;
            outline: none;
        }


        .input-item::placeholder {
            text-transform: uppercase;
        }

        .btn {
            text-align: center;
            padding: 10px;
            width: 100%;
            margin-top: 40px;
            background-image: linear-gradient(to right, #a6c1ee, #fbc2eb);
            color: #fff;
        }

        .msg {
            text-align: center;
            line-height: 88px;
        }

        a {
            text-decoration-line: none;
            color: #abc1ee;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="div_container">
        <div class="login-wrapper">
            <div ><a class="btn-primary btn-xs" href="{% url 'home' %}">home</a></div>

            <div class="header">Login</div>
            <div class="form-wrapper">
                {% csrf_token %}
                <input type="text" name="username" id="id_username" placeholder="username" class="input-item">
                <input type="password" name="password" id="id_password" placeholder="password" class="input-item">

                <div class="btn" id="put">Login</div>
            </div>
            <div class="msg">
                你没有登录？
                <a href="{% url 'notebook:register' %}">注册</a>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
    <script>
        $("#put").click(function () {
            var username = $("#id_username").val()
            var password = $("#id_password").val()

            $.ajax({
                url: "",
                type: "post",
                dataType: "json",
                data: {
                    "username": username,
                    "password": password,
                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                },
                success: function (args) {
                    if (args.code === 200) {
                        window.location.href = "{% url 'home' %}"
                    } else {
                        alert(args.msg)
                    }
                }
            })


        })


    </script>
{% endblock %}